name: Publish ROCK
on:
  push:
    branches:
      - 8.0-22.04
  workflow_dispatch:
    branches:
      - 8.0-22.04

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - name: Install yq
        run: |
          sudo snap install yq
      - uses: actions/download-artifact@v3
        with:
          name: charmed-mysql-rock

#      - name: Log in to registry
#        # This is where you will update the personal access token to GITHUB_TOKEN
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Import and push to Docker Hub
        run: |
          version="$(cat rockcraft.yaml | yq e '.version')"
          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"charmed-mysql_${version}_amd64.rock" \
            docker-daemon:"ghcr.io/taurus-forever/charmed-mysql:${version}"
          docker push "ghcr.io/taurus-forever/charmed-mysql:${version}"
